<?php
translator::tlschema("faq");
popup_header("General Questions with Spoilers");
$c = translator::translate_inline("Return to Contents");
rawoutput("<a href='petition.php?op=faq'>$c</a><hr>");
output::doOutput("`n`n`&(Warning, the FAQs below might contain some spoilers, so if you really want to discover things on your own, you'd be better off not reading too far.");
output::doOutput("This is not a manual.  It's a self-help pamphlet.)`n`n`n`n`n`n`n`n`n`n`n`n`n");
output::doOutput("`^1. What are gems for?`n");
output::doOutput("`@Gems are magical portals into the future. Gaze into the depths of a gem and you can see that which is to come.`n");
output::doOutput("Gullible? We sure hope not!`n");
output::doOutput("Lots of people love those little gemstones and are willing to trade things for them.");
output::doOutput("Your local bartender is something of a gemologist.`n`n");
output::doOutput("`^2. How do you get gems?`n");
output::doOutput("`@To the mines with you!!`n");
output::doOutput("Actually, you can't mine them.  (Well, you can, but only if you get lucky and find the mine. Warning though, mines can be dangerous.)");
output::doOutput("Gems can be found in the forest during 'special events' that happen randomly - if you play often enough, you're bound to stumble across one at some point.");
output::doOutput("Gems can also be gained very occasionally from a forest fight.`n`n");
output::doOutput("`^3. Why do some people seem to have so many hitpoints at a low level?`n");
output::doOutput("`@Cause they're bigger than you.`n");
output::doOutput("No, really, they *are* bigger than you. You'll be big too someday.`n`n");
output::doOutput("`^4. Does that have something to do with the titles that people have?`n");
output::doOutput("`@But of course!`n");
output::doOutput("Indeed, every time you kill the dragon, you return to level one.");
output::doOutput("If you kill the dragon enough times, you get a new title.");
output::doOutput("So low level players with titles have had opportunities to embiggen themselves. (see Hall of Fame)`n`n");
output::doOutput("`^5. What's a buff?`n");
output::doOutput("`@It's what we use to shine our shoes.`n");
output::doOutput("Did you think it was some sort of temporary or permanent effect which affects your stats in a positive or negative manner? Hah!`n`n");
output::doOutput("`^6. Why does that old man keep hitting me with an ugly/pretty stick in the forest?`n");
output::doOutput("`@You look like a pi&ntilde;ata!`n",true);
output::doOutput("It's a special event that can add or remove charm.`n`n");
output::doOutput("`^7. Well, what's the point of charm?`n");
output::doOutput("`@To get chicks (or guys).`n");
output::doOutput("Well, actually, that *is* the point.");
output::doOutput("Visit some folks at the Inn, and you ought to be able to figure this one out.");
output::doOutput("The more charm you have, the more successful you'll be at wooing said folks.`n`n");
output::doOutput("`^8. Okay, I saw the man in the forest and he hit me with his ugly stick, but it says I'm uglier than the stick, and I made it lose a charm point. What's going on?`n");
output::doOutput("`@You're clearly the least charming person on the planet.");
output::doOutput("And if you're the person who actually *asked* this question, you're also the dumbest.");
output::doOutput("Use a little power of inference, wouldja?");
output::doOutput("No. Really.`n");
output::doOutput("Okay, we did say you were the dumbest, so: it means you currently have zero charm points.`n`n");
output::doOutput("`^9. How do I check my charm?`n");
output::doOutput("`@Take a peek in the mirror once in a while.`n");
output::doOutput("We jest - there's no mirror.");
output::doOutput("You'll have to ask a friend how you look today - the responses may be vague, but they'll give you a clue how you're doing.`n`n");
output::doOutput("`^10. Who is the Management?`n");
output::doOutput("`@Appleshiner, Foilwench and Catscradler are in charge of this FAQ, but if something goes wrong, blame MightyE or Kendaer.");
output::doOutput("They're in charge of everything else.");
output::doOutput("To get ahold of them, or one of their trusty helpers, use the Petition for Help link.`n`n");
output::doOutput("`^11. How did they get to be so darn attractive, anyway?`n");
output::doOutput("`@Lots of at-home facials, my dear!!");
output::doOutput("MightyE especially enjoys the Grapefruit Essence Facial Masque.`n");
rawoutput("<hr><a href='petition.php?op=faq'>$c</a>");
